name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        python setup.py install
    
    - name: Run tests with unittest
      run: |
        python -m coverage run -m unittest discover -s tests
        python -m coverage xml
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      if: github.event_name == 'push'